# every text should have a category, and the last category should be the name of the book
#every category have a name in English, a name in Tibetan, a description in English, a short description in English, a description in Tibetan, and a short description in Tibetan

categories:
  - enName: "Liturgy"
    boName: "ཆོ་ག"
    enDesc: ""
    enShortDesc: "Prayers and rituals"
    boDesc: ""
    boShortDesc: "ཆོ་ག་དང་འདོན་ཆ།"
    
  - enName: "Commentaries"
    boName: "འགྲེལ་པ།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""

  - enName: ""
    boName: "བྱང་གཏེར་དགོངས་པ་ཟང་ཐལ་གྱི་རྒྱུད་ཆེན་ལས་བྱུང་བའི་ཀུན་བཟང་སྨོན་ལམ་གྱི་རྣམ་བཤད། ཀུན་བཟང་ཉེ་ལམ་འོད་སྣང་གསལ་བའི་སྒྲོན་མ།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""
    
  - enName: ""
    boName: "སྨོན་ལམ་ཀློག་པ་དང་ཐོས་པའི་ཕན་ཡོན་བསྟན་པ།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""
    
  - enName: ""
    boName: "རྫོགས་ཆེན་གྱི་ལམ་ལ་བརྟན་པ་ཐོབ་པའི་རྣལ་འབྱོར་པས་བསམ་པས་ཇི་ལྟར་སྨོན་པ་དང་སྦྱོར་བ་ཚིག་ཉན་ཀློག་བྱས་པའི་ཕན་ཡོན་དངོས།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""
    
