categories:
  - enName: "Madyamika"
    boName: "དབུ་མ།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""

  - enName: "Root text"
    boName: "རྩ་བ།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""

  - enName: "The Way of the Buddhisattva"
    boName: "སྤྱོད་འཇུག"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""