categories:
  - enName: "Liturgy"
    boName: "ཆོ་ག"
    enDesc: "Prayers and rituals"
    enShortDesc: "Prayers and rituals"
    boDesc: "ཆོ་ག་དང་འདོན་ཆ།"
    boShortDesc: "ཆོ་ག་དང་འདོན་ཆ།"

  - enName: "Prayers"
    boName: "སྨོན་ལམ།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""

  - enName: "Prayer for the Future of the Dharma"
    boName: "བསྟན་འབར་མ།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""