# every text should have a category, and the last category should be the name of the book
#every category have a name in English, a name in Tibetan, a description in English, a short description in English, a description in Tibetan, and a short description in Tibetan

categories:
  - enName: "Liturgy"
    boName: "ཆོ་ག"
    enDesc: ""
    enShortDesc: "Prayers and rituals"
    boDesc: ""
    boShortDesc: "ཆོ་ག་དང་འདོན་ཆ།"

  - enName: "Prayers"
    boName: "སྨོན་ལམ།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""


  - enName: "" # last category should be the name of the book
    boName: "ཀུན་བཟང་སྨོན་ལམ་གྱི་འདྲེན་བྱེད་ཊྰི་ཀའི་ཐུར་མས་བསལ་བ།" # name of the book in Tibetan
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: "ཊྰི་ཀའི་ཐུར་མས་བསལ་བ།"
