# every text should have a category, and the last category should be the name of the book
#every category have a name in English, a name in Tibetan, a description in English, a short description in English, a description in Tibetan, and a short description in Tibetan
categories:
  - enName: "Madyamika"
    boName: "དབུ་མ།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""

  - enName: "The Way of the Boddhisattva" # last category should be the name of the book
    boName: "སྤྱོད་འཇུག།" # name of the book in Tibetan
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""

  - enName: "Commentaries"
    boName: "འགྲེལ་པ།"
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""


  - enName: "The commentary on the difficult points of the Introduction to the Bodhisattvas Way of Life" # last category should be the name of the book
    boName: "བྱང་ཆུབ་ཀྱི་སྤྱོད་པ་ལ་འཇུག་པའི་དཀའ་འགྲེལ།" # name of the book in Tibetan
    enDesc: ""
    enShortDesc: ""
    boDesc: ""
    boShortDesc: ""
    base_text_titles: ["The Way of the Boddhisattva"]
    base_text_mapping: "many_to_one"
    link: "Commentary"


